version: '3.8'

services:
  django_app:
    build: .
    container_name: django_todo_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
